import "./globals.css";

import { Providers } from "@/components/Providers";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const runtime = process.env.NODE_ENV === "production" ? "edge" : "node";

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <Toaster expand={true} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
